spring.application.name=prueba
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=7364
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
app.security.jwt.secret=change-this-secret-key-for-jwt-signing-2026-super-long
app.security.jwt.access-token-expiration=900000
app.security.jwt.refresh-token-expiration=604800000

# Perfil alterno para reconstruir el esquema desde cero:
#   mvnw spring-boot:run "-Dspring-boot.run.profiles=reset"
# Muestra absolutamente todo lo que pasa en Spring
logging.level.root=ERROR
logging.level.org.springframework=DEBUG
# Específicamente para ver errores de Hibernate/Base de datos
logging.level.org.hibernate.SQL=DEBUG
# Para ver los parámetros de las consultas
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
